spring:
  application:
    name: BookApp
  datasource:
    url: jdbc:mysql://localhost:3306/books_dev?useSSL=false
    username: root
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  elasticsearch:
    rest:
      uris: http://localhost:9200

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

server:
  port: 8090
  error:
    include-stacktrace: never
    include-binding-errors: always
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always


