spring:
  application:
    name: SearchApp
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: books-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  main:
    allow-bean-definition-overriding: true

server:
  port: 8070
  error:
    include-stacktrace: never
    include-binding-errors: always
    include-message: always



elasticsearch:
  hosts: https://localhost:9200
  ssl:
    certificate: /Users/samyakmoon/Documents/elasticsearch.crt
    certificate-password: changeit

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
